spring:
  application:
    name: otel-demo
  docker:
    compose:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true # https://docs.spring.io/spring-boot/reference/actuator/observability.html#actuator.observability.annotations