spring:
  application:
    name: otel-demo
  threads:
    virtual:
      enabled: false
  docker:
    compose:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
  observations:
    annotations:
      enabled: true # https://docs.spring.io/spring-boot/reference/actuator/observability.html#actuator.observability.annotations
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
