# Use the official OpenTelemetry Collector Contrib base image
FROM otel/opentelemetry-collector-contrib:latest

# Set the working directory
WORKDIR /etc/otelcol-contrib

# Copy the OpenTelemetry Collector configuration file
COPY otel-config.yaml /etc/otelcol-contrib/config.yaml

